name: Deploy Svelte

on:
    push:
        branches:
            - main

jobs:
    deploy-svelte:
        runs-on: ubuntu-latest
        name: Deploy Svelte
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn example-build:svelte
            - name: Publish
              uses: cloudflare/wrangler-action@1.2.0
              env:
                  USER: root
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  workingDirectory: "examples/svelte"
